version: '3.2'

services:
    api:
        build: api
        container_name: piston_api
        restart: always
        ports:
            - 2000:2000
        volumes:
            - ./data/piston/packages:/piston/packages
        environment:
            - PISTON_REPO_URL=http://repo:8000/index
        tmpfs:
            - /piston/jobs:exec,uid=1000,gid=1000,mode=711
            - /tmp:exec

    repo: # Local testing of packages
        build: repo
        container_name: piston_repo
        command: ['makec-12.2.0']
        volumes:
            - .:/piston
